**Inventory Intelligence : Knowing What to Stock and When to Reorder**

- Problem statement :

    An online retailer has no clear rule for when to reorder. Some products run out and lose sales. Others pile up and tie up cash.

- Objective :

    Use two years of sales history to show, for every product, how much backup stock to keep, when to reorder, and which products need the most attention.

In [1]:
# import libraries

import pandas  as pd
import numpy as np
import matplotlib.pyplot as mp
import seaborn as sb 
from scipy import stats
import statsmodels.api as sm
import csv

In [2]:
df = pd.read_csv('cleaned_retail.csv',dtype={'Invoice': str})

In [3]:
df.head()

,Unnamed: 0,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [4]:
df.info()
df.drop(columns='Unnamed: 0',inplace = True)

<class 'pandas.DataFrame'>
RangeIndex: 1041670 entries, 0 to 1041669
Data columns (total 10 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Unnamed: 0   1041670 non-null  int64
 1   Invoice      1041670 non-null  str
 2   StockCode    1041670 non-null  str
 3   Description  1041670 non-null  str
 4   Quantity     1041670 non-null  int64
 5   InvoiceDate  1041670 non-null  str
 6   Price        1041670 non-null  float64
 7   Customer ID  805549 non-null   float64
 8   Country      1041670 non-null  str
 9   Revenue      1041670 non-null  float64
dtypes: float64(3), int64(2), str(5)
memory usage: 149.3 MB

In [5]:
df.head()
df.shape

(1041670, 9)

In [6]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

# **Total SKUs (4,746)** — The total number of different products being tracked

In [7]:
# Remove Trailing Space
with_trail_spaces = df['StockCode'].copy()

without_trail_space = (df['StockCode'].astype(str).str.strip().str.upper())

print(f'Unique values before cleaning: {with_trail_spaces.nunique()}')
print(f'Unique values after cleaning: {without_trail_space.nunique()}')

Unique values before cleaning: 4918
Unique values after cleaning: 4746

In [8]:
# Apply cleaning permanently to the original column
df['StockCode'] = without_trail_space
print(len(df))

1041670

In [9]:
# Extract Date 
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])
df['Date']=df['InvoiceDate'].dt.date
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Date
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009-12-01

# **Total quantity sold per SKU per day**

In [10]:

daily_demand = df.groupby(['StockCode','Description','Date'])['Quantity'].sum().reset_index()
daily_demand.rename(columns={'Quantity':'DailyQty'},inplace='True')
print(daily_demand.shape)
print(daily_demand.head(10).to_string(index=False))
daily_demand.to_csv("daily_demand.csv",index=False)

(533346, 4)
StockCode                 Description       Date  DailyQty
    10002 INFLATABLE POLITICAL GLOBE  2009-12-01        12
    10002 INFLATABLE POLITICAL GLOBE  2009-12-03         7
    10002 INFLATABLE POLITICAL GLOBE  2009-12-04        73
    10002 INFLATABLE POLITICAL GLOBE  2009-12-06        49
    10002 INFLATABLE POLITICAL GLOBE  2009-12-07         2
    10002 INFLATABLE POLITICAL GLOBE  2009-12-08        12
    10002 INFLATABLE POLITICAL GLOBE  2009-12-10         1
    10002 INFLATABLE POLITICAL GLOBE  2009-12-11         9
    10002 INFLATABLE POLITICAL GLOBE  2009-12-14        37
    10002 INFLATABLE POLITICAL GLOBE  2009-12-21        12

In [11]:
df_2 = pd.read_csv('daily_demand.csv',dtype={'StockCode': str})
df_2.head()
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 533346 entries, 0 to 533345
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   StockCode    533346 non-null  str
 1   Description  533346 non-null  str
 2   Date         533346 non-null  str
 3   DailyQty     533346 non-null  int64
dtypes: int64(1), str(3)
memory usage: 37.6 MB

# **How many days of dataset**

In [12]:

df['Date']=pd.to_datetime(df['Date'])

full_date_range=pd.date_range(df_2['Date'].min(),df_2['Date'].max())
total_days = len(full_date_range)
print(f"Total days in dataset : {total_days}")

Total days in dataset : 739

# **For each SKU , total quantity sold and count of days  it appeared**

In [13]:

sku_stats=df_2.groupby(['StockCode','Description']).agg(
    TotalQtySold =('DailyQty','sum'),
    DaysWithSales=('DailyQty','count'),
    StdDevOnSaleDays=('DailyQty','std')
).reset_index()

print(sku_stats.to_string(index=False))

   StockCode                         Description  TotalQtySold  DaysWithSales  StdDevOnSaleDays
       10002         INFLATABLE POLITICAL GLOBE           8836            225         93.088631
      10002R               ROBOT PENCIL SHARPNER             4              3          0.577350
       10080            GROOVY CACTUS INFLATABLE           315             26         11.032051
       10109                BENDY COLOUR PENCILS             4              1               NaN
       10120                        DOGGY RUBBER           680             64         12.946164
      10123C               HEARTS WRAPPING TAPE            654             56         29.637879
      10123G             ARMY CAMO WRAPPING TAPE          2251             15        387.311515
      10124A         SPOTS ON RED BOOKCOVER TAPE            62             18          2.254987
      10124G            ARMY CAMO BOOKCOVER TAPE            38             10          2.573368
       10125             MINI FUNKY DESIGN TAPES          2151            124         23.029512
       10133        COLOURING PENCILS BROWN TUBE          3882            188         25.367758
       10134        COLOURING PENCILS BROWN TUBE           627             45         34.241389
       10135        COLOURING PENCILS BROWN TUBE          4273            228         51.826368
       10138           ASSORTED COLOUR JUMBO PEN           261             18         21.815402
       11001         ASSTD DESIGN RACING CAR PEN          4885            192         58.574666
       15030                    FAN BLACK FRAME            254             26         11.075406
       15034         PAPER POCKET TRAVELING FAN          10266            201        134.091235
       15036           ASSORTED COLOURS SILK FAN         44365            433        214.316666
       15039                      SANDALWOOD FAN          5119            222         47.955873
      15044A                 PINK PAPER PARASOL           4970            189        255.107814
      15044B                 BLUE PAPER PARASOL           1673            150         43.262541
      15044C                PURPLE PAPER PARASOL           973            181          8.503089
      15044D                   RED PAPER PARASOL          1598            181         15.142598
     15056BL             EDWARDIAN PARASOL BLACK          9772            443         61.309032
      15056N           EDWARDIAN PARASOL NATURAL         11550            485         55.474015
      15056P              EDWARDIAN PARASOL PINK          2579            274         38.492109
      15058A        BLUE POLKADOT GARDEN PARASOL           200             64          2.962731
      15058A     BLUE WHITE SPOTS GARDEN PARASOL           276             44          7.209050
      15058B        PINK POLKADOT GARDEN PARASOL           234             70          4.751463
      15058B     PINK WHITE SPOTS GARDEN PARASOL           204             43          5.219437
      15058C     ICE CREAM DESIGN GARDEN PARASOL           470            101          6.763779
      15059A      ENGLISH ROSE EDWARDIAN PARASOL           509              3        290.407185
      15060B          FAIRY CAKE DESIGN UMBRELLA          1443            293          6.213206
       16008 SMALL FOLDING SCISSOR(POINTED EDGE)          3143             71         64.926323
       16010  FOLDING CAMPING SCISSOR W/KNIF & S            44              4          9.591663
       16011                     ANIMAL STICKERS           385             12         11.758620
       16011                     ANIMAL STICKERS          3521             93         35.267176
       16012          FOOD/DRINK SPONGE STICKERS          2214             55         33.042743
       16012          FOOD/DRINK SPUNGE STICKERS           759             18         59.194843
       16014         SMALL CHINESE STYLE SCISSOR         30370             87        771.570314
       16015        MEDIUM CHINESE STYLE SCISSOR          1573             60         42.314838
       16016         LARGE CHINESE STYLE SCISSOR          2338             98         38.101871
      16020C           CLEAR STATIONERY BOX SET            160             34          5.323074
       16033               MINI HIGHLIGHTER PENS         15121             46        562.515488
       16043           POP ART PUSH DOWN RUBBER           2145             13        353.343789
       16044            POP-ART FLUORESCENT PENS          6193              3       3533.173125
       16045          POPART WOODEN PENCILS ASST          9312             62        132.535283
       16046             TEATIME PEN CASE & PENS         10061             55        868.017577
       16047             POP ART PEN CASE & PENS         10614             28       1357.183738
       16048     TEATIME ROUND PENCIL SHARPENER           3462             88         97.904350
       16049               TEATIME GEL PENS ASST          3169             28        152.930644
       16050          TEATIME PENCIL WITH RUBBER           151              7         20.807508
       16051         TEATIME PENCIL W STAMP ASST           941              4        420.787654
       16052            TEATIME PUSH DOWN RUBBER           850             33         55.036937
       16053       POPART COL BALLPOINT PEN ASST          4313             10        826.957751
       16054   POPART RECT PENCIL SHARPENER ASST          1210             35         30.722942
       16119             FUNKY GIRL ADDRESS BOOK           273              6         61.389739
      16151A FLOWER DES BLUE HANDBAG/ORANG HANDL             3              2          0.707107
      16151A     FLOWERS HANDBAG blue and orange            49              3         23.115651
      16156L                       WRAP CAROUSEL           375             13         13.867505
      16156L                      WRAP, CAROUSEL           575             21          7.519815
      16156N           WRAP, FRIENDSHIP ON GREEN          1475             47         12.189720
      16156S              WRAP PINK FAIRY CAKES          16761            283         81.082777
      16161C                  WRAP SPEED DEMONS            450              2        176.776695
      16161E                       WRAP BOUDOIR            750              7        185.244369
      16161G                   WRAP BAD HAIR DAY           975             32         15.206078
      16161M                    WRAP  PINK FLOCK          1075             37         11.045225
      16161P                  WRAP ENGLISH ROSE          13298            283         44.284900
      16161U               WRAP SUKI AND FRIENDS          6726            160         57.720416
      16161U               WRAP,SUKI AND FRIENDS          3350             83         45.837619
      16162L                   THE KING GIFT BAG          8101             25       1031.271565
      16162M        THE KING GIFT BAG 25x24x12cm            88             12          4.313474
      16168M        FUNKY MONKEY GIFT BAG MEDIUM          1713             89         41.413733
      16168S         FUNKY MONKEY GIFT BAG SMALL          1283              9        230.422498
      16169A            WRAP CHRISTMAS DECOUPAGE            25              1               NaN
      16169C                  WRAP BLUE REINDEER          1350             32         27.995895
      16169D                  WRAP WINTER FOREST           250              5         25.000000
      16169E                WRAP 50'S  CHRISTMAS          4563             83         49.533181
      16169F                       WRAP BLIZZARD           975             26         17.677670
      16169G             WRAP ROMANTIC DECOUPAGE            25              1               NaN
      16169K                       WRAP FOLK ART          2100             52         69.690113
      16169M                  WRAP DAISY CARPET           2060             54         64.722166
      16169N           WRAP BLUE RUSSIAN FOLKART          2050             49         78.459742
      16169P         WRAP GREEN RUSSIAN FOLKART           1750             46         70.067255
       16192       PINK BALLET OPENING CUBE BOX              3              1               NaN
      16201A             PASTEL PINK PHOTO ALBUM           101              7         12.122392
      16201B             PASTEL BLUE PHOTO ALBUM            34              4         10.472185
      16202A            PASTEL PINK PHOTO ALBUM            663             21         89.319411
      16202B            PASTEL BLUE PHOTO ALBUM           1039             22        128.712649
      16202C                   BEIGE PHOTO ALBUM            97             12          8.184890
      16202E                  BLACK PHOTO ALBUM             82             14          5.274863
      16206B           RED PURSE WITH PINK HEART            96             15          6.299660
      16207A            PINK STRAWBERRY HANDBAG            143             67          1.650487
      16207B              PINK HEART RED HANDBAG           265             30         23.587085
       16212  FUNKY GIRLZ ASST MAGNETIC MEMO PAD           375             35         12.814448
       16215    FUNKY GIRLZ MAGNETIC TO DO LIST              8              1               NaN
       16216       LETTER SHAPE PENCIL SHARPENER          4158             77        184.515582
       16218          CARTOON  PENCIL SHARPENERS          4632             84         70.463550
       16219        HOUSE SHAPE PENCIL SHARPENER          3358            107         77.391146
       16225                   RATTLE SNAKE EGGS          1530            127         33.370897
       16235  RECYCLED PENCIL WITH RABBIT ERASER          5943            220         50.942037
       16236                KITTY PENCIL ERASERS          2666            197         17.495340
       16237                SLEEPING CAT ERASERS         10938            337         54.092833
       16238           PARTY TIME PENCIL ERASERS          2525            181         16.972290
       16239         BALLERINA HEART DECORATION.           347             16         72.298196
      16243B       BROWN COZY SQUARE PHOTO ALBUM           212              6         83.123202
      16244A MAXWELL 2 TONE PINK 60 PAGE PHOTO A           186             24         19.505295
      16244B MAXWELL 2 TONE BLUE 60 PAGE PHOTO A           345             26         48.527566
      16245A     PINK MINI STATIONERY SET W CASE            11              6          1.329160
      16248B                     BLUE HOLE PUNCH            82             11         13.822906
       16254  TRANSPARENT ACRYLIC TAPE DISPENSER           941             32        152.323056
      16256B FLOWER PENCIL/RUBBER+5 MINI PENCILS           524             34         16.856107
      16256C HEARTS PENCIL/RUBBER+5 MINI PENCILS           169             10         14.601750
      16258A      SWIRLY CIRCULAR RUBBERS IN BAG          1080             87         23.140899
      16258B                DAISY ERASERS IN BAG          1017             10        161.670481
       16259        PIECE OF CAMO STATIONERY SET          5473             51         84.236451
       17001  HEAVENS SCENT FRAGRANCE OILS ASSTD          1211             21         91.504827
       17003                 BROCADE RING PURSE          71430            301        833.547716
      17007B S/3 POT POURI CUSHIONS BLUE COLOURS            46              6          8.959167
      17011A     ORIGAMI VANILLA INCENSE+FLOWER            261             12         37.336614
      17011B     ORIGAMI JASMINE INCENSE+FLOWER             19              2          9.192388
      17011C     ORIGAMI LAVENDER INCENSE+FLOWER           335              2        235.466558
      17011D         ORIGAMI ROSE INCENSE+FLOWER           209              4         93.400125
      17011E  ORIGAMI OPIUM SCENT INCENSE+FLOWER           124              1               NaN
      17011F   ORIGAMI SANDLEWOOD INCENSE+FLOWER           386             20         42.509565
      17012A ORIGAMI VANILLA INCENSE/CANDLE SET            731             82         24.392471
      17012B  ORIGAMI JASMINE INCENSE/CANDLE SET           728            110         14.469190
      17012C ORIGAMI LAVENDER INCENSE/CANDL SET            862             95         29.276104
      17012D    ORIGAMI ROSE INCENSE/CANDLE SET            524             94          8.072906
      17012E   ORIGAMI OPIUM INCENSE/CANDLE SET            294             25         38.935074
      17012F ORIGAMI SANDLEWOOD INCENSE/CAND SET           591             85         13.087531
      17013B     ORIGAMI JASMINE INCENSE IN TUBE           256              3         73.077584
      17013C    ORIGAMI LAVENDER INCENSE IN TUBE           213              2         14.849242
      17013D        ORIGAMI ROSE INCENSE IN TUBE          1069             31         49.553924
      17013F  ORIGAMI SANDLEWOOD INCENSE IN TUBE            62              5         24.388522
      17014A       ORIGAMI VANILLA INCENSE CONES           277             15         30.988170
      17014C      ORIGAMI LAVENDER INCENSE CONES            97              2         67.175144
      17014D          ORIGAMI ROSE INCENSE CONES           479              8         86.853633
      17014E         ORIGAMI OPIUM INCENSE CONES            95              6         35.846432
      17014F    ORIGAMI SANDLEWOOD INCENSE CONES            61              4         27.837325
       17021              NAMASTE SWAGAT INCENSE          4436             70        171.939252
      17027A             INCENSE BAZAAR CANNABIS           228              2         42.426407
      17028J                INCENSE BAZAAR PEACH             6              1               NaN
       17033     BROCADE PURSE,SMALL ARCH BUTTON          3280             56         92.267173
       17038      PORCELAIN BUDAH INCENSE HOLDER          2659             55         58.745281
       17039          INLAID WOOD INCENSE HOLDER          3707             39        208.971661
       17061   ASSORTED SHAPED STENCIL FOR HENNA            52              1               NaN
      17084A          TRANQUILITY MASALA INCENSE           442             18          8.368163
      17084G                        MOON INCENSE            50              2          0.000000
      17084J          LOVE POTION MASALA INCENSE           481             20         12.180550
      17084N               FAIRY DREAMS INCENSE           2798            156         28.508896
      17084P               DRAGONS BLOOD INCENSE          1041             63         27.667879
      17084R               ASSORTED INCENSE PACK         12137             64        417.101197
      17090A    LAVENDER INCENSE 40 CONES IN TIN           215             26         14.750072
      17090D     VANILLA INCENSE 40 CONES IN TIN            95             28          3.281139
      17091A             LAVENDER INCENSE IN TIN          2096             97         40.767010
      17091B          JASMINE TEA INCENSE IN TIN           282             45          9.264792
      17091F           SANDALWOOD INCENSE IN TIN            19              7          1.603567
      17091J              VANILLA INCENSE IN TIN          4086            144         43.110506
       17096   ASSORTED LAQUERED INCENSE HOLDERS          6243             68        266.275991
      17107D        FLOWER FAIRY 5 DRAWER LINERS            60             17          1.972234
      17107D   FLOWER FAIRY 5 SUMMER DRAW LINERS             6              1               NaN
      17107D FLOWER FAIRY,5 SUMMER B'DRAW LINERS           270             58          3.353719
      17108D  FLOWER FAIRY SUMMER BOUQUET SACHET           355             22          9.612965
      17109A           FLOWER FAIRY INCENSE LILY           709             13         85.786183
      17109B       FLOWER FAIRY INCENSE LAVENDER          4542             15        994.884502
      17109C           FLOWER FAIRY INCENSE ROSE          3124             12        716.745718
      17109D        FLOWER FAIRY INCENSE BOUQUET          1260             36         78.277528
      17129C   SKY BLUE COLOUR GLASS GEMS IN BAG            87             11         21.262430
      17129D      CLEAR COLOUR GLASS GEMS IN BAG          1125             30         69.878096
      17129F              BLUE GLASS GEMS IN BAG           915             75         17.825733
      17129F         DEEP BLUE GLASS GEMS IN BAG           669             57         14.558412
      17136A      BLUE STONES ON WIRE FOR CANDLE           795             33         20.961816
      17164B   ASS COL SMALL SAND GECKO P'WEIGHT          1632             67         43.146931
      17164D    ASS COL SMALL SAND FROG P'WEIGHT          1159             23         86.299552
      17165B   ASS COL LARGE SAND GECKO P'WEIGHT           813             47         44.301789
      17165D    ASS COL LARGE SAND FROG P'WEIGHT           723             68         17.434658
       17174              ASSTD RASTA KEY-CHAINS            36              6          8.944272
       17178            FLAT PALM T-LIGHT HOLDER           133             23          6.687550
       17181     CIRCLE OF FRIENDS CANDLE HOLDER           354             47         13.731669
      17191A  ROSE FLOWER CANDLE+INCENSE 16X16CM            33             12          1.484771
       18007 ESSENTIAL BALM 3.5g TIN IN ENVELOPE         11424             62        610.215064
       18010    ASSORTED FRAGRANCE BATH CONFETTI            64              8          7.071068
      18094C   WHITE AND BLUE CERAMIC OIL BURNER           413             72          5.651855
      18094C  WHITE/BLUE RECT CERAMIC OIL BURNER            33             12          2.490893
      18096C WHITE ROUND PORCELAIN TLIGHT HOLDER           131             18         10.648422
      18097A PINK TALL PORCELAIN T-LIGHT HOLDER             19             11          0.786245
      18097B  BLUE TALL PORCELAIN T-LIGHT HOLDER             7              3          1.154701
      18097C WHITE TALL PORCELAIN T-LIGHT HOLDER          1818            162         29.638610
      18098A     PINK PORCELAIN B'FLY OIL BURNER             2              2          0.000000
      18098B     BLUE PORCELAIN B'FLY OIL BURNER             3              3          0.000000
      18098C      PORCELAIN BUTTERFLY OIL BURNER          1596            196         11.120321
       20615        BLUE POLKADOT PASSPORT COVER           331             87          5.732078
       20615          BLUE SPOTTY PASSPORT COVER           316             57         13.575280
       20616       CHERRY BLOSSOM PASSPORT COVER           287             99          5.559502
       20617         FIRST CLASS PASSPORT COVER            499             95         20.529672
       20618  QUEEN OF THE SKIES PASSPORT COVER            299            117          2.832826
       20619            TROPICAL PASSPORT COVER            580            157          9.304440
       20620           RED SPOTTY PASSPORT COVER            15             11          0.674200
       20621             ECONOMY PASSPORT COVER            208             31         17.757991
       20622                 VIP PASSPORT COVER             43             15          3.642344
       20622                  VIPPASSPORT COVER            547             93         21.200312
       20652          BLUE POLKADOT LUGGAGE TAG            287             74          4.174130
       20652            BLUE SPOTTY LUGGAGE TAG           1238             57         82.723022
       20653          CHERRY BLOSSOM LUGGAGE TAG          2006             70        214.812752
       20654            FIRST CLASS LUGGAGE TAG            400            107          4.541915
       20655          QUEEN OF SKIES LUGGAGE TAG           421            148          3.155198

# **Average daily demand** : How many units of a product typically sell per day

In [14]:

sku_stats['AvgDailyDemand']=sku_stats['TotalQtySold'] / total_days
sku_stats['AvgDailyDemand_ActiveDays'] = sku_stats['TotalQtySold'] / sku_stats['DaysWithSales']

In [15]:

sku_stats['StdDevOnSaleDays']=sku_stats['StdDevOnSaleDays'].fillna(0)

In [16]:
# print(sku_stats)
print(sku_stats.shape)
print(sku_stats.sort_values(by='TotalQtySold',ascending=False).head(10).to_string(index=False))
sku_stats.to_csv('sku_stats.csv',index=False)

(5432, 7)
StockCode                        Description  TotalQtySold  DaysWithSales  StdDevOnSaleDays  AvgDailyDemand  AvgDailyDemand_ActiveDays
    84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS        110138            470        527.825601      149.036536                 234.336170
   85123A WHITE HANGING HEART T-LIGHT HOLDER         96677            602        219.121933      130.821380                 160.593023
    84879      ASSORTED COLOUR BIRD ORNAMENT         81809            582        243.664243      110.702300                 140.565292
    23843        PAPER CRAFT , LITTLE BIRDIE         80995              1          0.000000      109.600812               80995.000000
   85099B            JUMBO BAG RED RETROSPOT         79279            461        198.299524      107.278755                 171.971800
    23166     MEDIUM CERAMIC TOP STORAGE JAR         78033            125       6635.405618      105.592693                 624.264000
    17003                BROCADE RING PURSE          71430            301        833.547716       96.657645                 237.308970
    21977 PACK OF 60 PINK PAISLEY CAKE CASES         56794            565        179.311968       76.852503                 100.520354
    84991        60 TEATIME FAIRY CAKE CASES         54716            559        136.863327       74.040595                  97.881932
    22197               SMALL POPCORN HOLDER         49948            375        329.948897       67.588633                 133.194667

In [17]:
# Look at the raw data for this specific product to see why it has 80k+ quantity in 1 day
df_2[df_2['StockCode'] == '23843']
sku_stats[sku_stats['StockCode'] == '23843']
# 'Paper Craft, Little Birdie' appears to be a top product by volume, it is an extreme outlier driven entirely by a single wholesale transaction of 80,995 units on a single day."

,StockCode,Description,TotalQtySold,DaysWithSales,StdDevOnSaleDays,AvgDailyDemand,AvgDailyDemand_ActiveDays
3349,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,1,0.0,109.600812,80995.0

In [18]:
df_3 =  pd.read_csv("sku_stats.csv")
df_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 5432 entries, 0 to 5431
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StockCode                  5432 non-null   str
 1   Description                5432 non-null   str
 2   TotalQtySold               5432 non-null   int64
 3   DaysWithSales              5432 non-null   int64
 4   StdDevOnSaleDays           5432 non-null   float64
 5   AvgDailyDemand             5432 non-null   float64
 6   AvgDailyDemand_ActiveDays  5432 non-null   float64
dtypes: float64(3), int64(2), str(2)
memory usage: 469.5 KB

# **Safety Stock** : Extra backup stock kept aside in case demand suddenly increases

In [19]:
lead_time_days = 7
service_level_z = 1.65
# Formula : Safety Stock = Z * StdDev(demand) * sqrt(Lead Time)
df_3['Safety_Stock'] = service_level_z * df_3['StdDevOnSaleDays'] * np.sqrt(lead_time_days)
df_3['Safety_Stock']=df_3['Safety_Stock'].round(0)

# **Reorder Point** — The stock level at which a new order should be placed

In [20]:
# formula : reorder point = ( avg daily demand * lead time) + safety stock
df_3['ReorderPoint'] = (df_3['AvgDailyDemand'] * lead_time_days) + df_3['Safety_Stock']
df_3['ReorderPoint']=df_3['ReorderPoint'].round(0)
print(df_3.sort_values(by='TotalQtySold', ascending=False).head(10).to_string(index=False))
df_3.to_csv("sku_reorder_point.csv",index=False)

StockCode                        Description  TotalQtySold  DaysWithSales  StdDevOnSaleDays  AvgDailyDemand  AvgDailyDemand_ActiveDays  Safety_Stock  ReorderPoint
    84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS        110138            470        527.825601      149.036536                 234.336170        2304.0        3347.0
   85123A WHITE HANGING HEART T-LIGHT HOLDER         96677            602        219.121933      130.821380                 160.593023         957.0        1873.0
    84879      ASSORTED COLOUR BIRD ORNAMENT         81809            582        243.664243      110.702300                 140.565292        1064.0        1839.0
    23843        PAPER CRAFT , LITTLE BIRDIE         80995              1          0.000000      109.600812               80995.000000           0.0         767.0
   85099B            JUMBO BAG RED RETROSPOT         79279            461        198.299524      107.278755                 171.971800         866.0        1617.0
    23166     MEDIUM CERAMIC TOP STORAGE JAR         78033            125       6635.405618      105.592693                 624.264000       28967.0       29706.0
    17003                BROCADE RING PURSE          71430            301        833.547716       96.657645                 237.308970        3639.0        4316.0
    21977 PACK OF 60 PINK PAISLEY CAKE CASES         56794            565        179.311968       76.852503                 100.520354         783.0        1321.0
    84991        60 TEATIME FAIRY CAKE CASES         54716            559        136.863327       74.040595                  97.881932         597.0        1115.0
    22197               SMALL POPCORN HOLDER         49948            375        329.948897       67.588633                 133.194667        1440.0        1913.0

In [21]:
df_4=pd.read_csv('sku_reorder_point.csv')
df_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 5432 entries, 0 to 5431
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StockCode                  5432 non-null   str
 1   Description                5432 non-null   str
 2   TotalQtySold               5432 non-null   int64
 3   DaysWithSales              5432 non-null   int64
 4   StdDevOnSaleDays           5432 non-null   float64
 5   AvgDailyDemand             5432 non-null   float64
 6   AvgDailyDemand_ActiveDays  5432 non-null   float64
 7   Safety_Stock               5432 non-null   float64
 8   ReorderPoint               5432 non-null   float64
dtypes: float64(5), int64(2), str(2)
memory usage: 554.4 KB

# **Asssumptions based Current Stock**
This dataset only has historical sales — it doesn't tell us what's sitting in the warehouse today. Real companies pull this from their inventory system, so here we simulate it realistically and document it clearly as an assumption.

In [22]:

np.random.seed(42)
df_4['SimulatedDaysOfStock']=np.random.randint(1,20,size=len(df_4))
df_4['CurrentStock'] = df_4['AvgDailyDemand'] * df_4['SimulatedDaysOfStock']

# **Reorder flag**

In [23]:

df_4['ReorderFlag'] = np.where(df_4['CurrentStock'] < df_4['ReorderPoint'],'Reorder Now','OK')
print(df_4['ReorderFlag'].value_counts().to_string())
print(f'\n{df_4.sort_values(by='TotalQtySold',ascending=False).head().to_string(index=False)}')
df_4.to_csv('final_inventory_analysis.csv',index=False)

ReorderFlag
Reorder Now    5084
OK              348

StockCode                        Description  TotalQtySold  DaysWithSales  StdDevOnSaleDays  AvgDailyDemand  AvgDailyDemand_ActiveDays  Safety_Stock  ReorderPoint  SimulatedDaysOfStock  CurrentStock ReorderFlag
    84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS        110138            470        527.825601      149.036536                 234.336170        2304.0        3347.0                    15   2235.548038 Reorder Now
   85123A WHITE HANGING HEART T-LIGHT HOLDER         96677            602        219.121933      130.821380                 160.593023         957.0        1873.0                    12   1569.856563 Reorder Now
    84879      ASSORTED COLOUR BIRD ORNAMENT         81809            582        243.664243      110.702300                 140.565292        1064.0        1839.0                     8    885.618403 Reorder Now
    23843        PAPER CRAFT , LITTLE BIRDIE         80995              1          0.000000      109.600812               80995.000000           0.0         767.0                    13   1424.810555          OK
   85099B            JUMBO BAG RED RETROSPOT         79279            461        198.299524      107.278755                 171.971800         866.0        1617.0                    18   1931.017591          OK

In [24]:
df_5 = pd.read_csv('final_inventory_analysis.csv')
df_5.info()

<class 'pandas.DataFrame'>
RangeIndex: 5432 entries, 0 to 5431
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StockCode                  5432 non-null   str
 1   Description                5432 non-null   str
 2   TotalQtySold               5432 non-null   int64
 3   DaysWithSales              5432 non-null   int64
 4   StdDevOnSaleDays           5432 non-null   float64
 5   AvgDailyDemand             5432 non-null   float64
 6   AvgDailyDemand_ActiveDays  5432 non-null   float64
 7   Safety_Stock               5432 non-null   float64
 8   ReorderPoint               5432 non-null   float64
 9   SimulatedDaysOfStock       5432 non-null   int64
 10  CurrentStock               5432 non-null   float64
 11  ReorderFlag                5432 non-null   str
dtypes: float64(6), int64(3), str(3)
memory usage: 737.0 KB

# **Total revenue per SKU**

In [25]:

transactions = pd.read_csv('cleaned_retail.csv',dtype={'Invoice' : str})
sku_revenue=transactions.groupby('StockCode')['Revenue'].sum().reset_index()
sku_revenue.rename(columns={'Revenue':'TotalRevenue'},inplace=True)
print(pd.pivot_table(sku_revenue,index='StockCode',values='TotalRevenue').to_string())

              TotalRevenue
StockCode
10002             7097.900
10002R              20.570
10080              129.290
10109                1.680
10120              146.100
10123C             257.010
10123G             165.560
10124A              26.040
10124G              16.380
10125             1758.200
10133             2407.590
10134              723.630
10135             4642.600
10138              111.220
11001             7509.970
15030               73.660
15034             1434.210
15036            33041.550
15039             4361.730
15044A           13228.550
15044B            4655.940
15044C            3050.880
15044D            4568.510
15056BL          48101.890
15056N           58427.590
15056P           12497.320
15056bl           1583.520
15056n            2259.440
15056p             628.720
15058A            3153.730
15058B            3327.670
15058C            2753.720
15059A            1567.000
15060B            6558.580
15060b              41.810
16008              423.460
16010                5.280
16011              819.060
16012              623.130
16014             9839.400
16015              711.880
16016             1891.100
16020C             134.500
16033             1544.520
16043              180.300
16044              389.220
16045              429.440
16046             1227.750
16047             1056.400
16048              537.180
16049              560.480
16050               46.450
16051               84.690
16052              283.000
16053              185.730
16054              159.000
16119              130.710
16151A              72.500
16156L             399.000
16156N             619.500
16156S            6600.620
16161C              45.000
16161E              75.000
16161G              97.500
16161M             449.500
16161P            5477.400
16161U            4105.920
16162L             570.430
16162M              36.960
16168M             525.010
16168S             126.830
16169A              10.500
16169C             567.000
16169D             105.000
16169E            1892.460
16169F             409.500
16169G              10.500
16169K             669.250
16169M             640.950
16169N             636.750
16169P             533.750
16192               12.900
16201A             213.370
16201B              81.100
16202A             296.000
16202B             528.560
16202C             230.590
16202E             162.730
16206B             116.400
16207A             423.530
16207B             457.650
16212              292.860
16215                5.200
16216              371.640
16218              454.520
16219              501.250
16225             1298.930
16235             1362.270
16236              599.310
16237             2337.660
16238              580.100
16239              492.170
16243B             441.770
16244A             479.410
16244B             765.020
16245A              13.750
16248B             102.500
16254              305.660
16256B             232.350
16256C              70.980
16258A             384.330
16258B             221.480
16259              766.090
17001              299.350
17003            14959.190
17007B              96.600
17011A             179.560
17011B              11.100
17011C             221.400
17011D             135.700
17011E              80.600
17011F             340.410
17012A             818.710
17012B             885.020
17012C             965.500
17012D             667.140
17012E             326.360
17012F             693.200
17013B             221.030
17013C              89.460
17013D             575.760
17013F              26.700
17014A             173.490
17014C              43.750
17014D             204.360
17014E              36.600
17014F              23.700
17021             1163.040
17027A              84.840
17028J               2.520
17033              867.840
17038              261.510
17039              837.880
17061                2.080
17084A              92.820
17084G              10.500
17084J             101.010
17084N             647.660
17084P             233.680
17084R            2213.970
17090A             220.750
17090D             113.950
17091A            1298.770
17091B             324.480
17091F              27.710
17091J            2297.990
17096             1117.940
17107D             856.800
17108D             149.100
17109A             333.610
17109B             896.340
17109C             661.230
17109D             603.380
17129C              58.830
17129D            1351.180
17129F            1691.220
17136A              65.940
17164B             651.600
17164D             450.780
17165B             754.830
17165D             689.670
17174               15.120
17178              156.650
17181              645.210
17191A             123.750
18007             1048.760
18010               30.160
18094C             616.910
18096C             314.000
18096c              41.140
18097A              48.450
18097B              17.850
18097C            4067.680
18098A               5.900
18098B               8.850
18098C            3375.760
18098c            1682.010
20615             1111.470
20616              461.880
20617              997.200
20618              652.740
20619             1020.730
20620               61.760
20621              453.770
20622             1152.830
20652             1041.060
20653              533.790
20654              507.910
20655              619.750
20657              728.970
20658             2308.930
20659              539.760
20660               91.250
20661              985.960
20662              476.350
20663              374.430
20664              155.410
20665             4377.370
20666              412.450
20667              108.690
20668             2570.810
20669             1153.200
20670              378.850
20671             1052.470
20672              201.000
20673                6.250
20674             4414.800
20675             8190.410
20676            13346.660
20677             9959.890
20678                6.600
20679            30667.320
20680               19.500
20681             4882.540
20682            10414.780
20683                3.250
20684             1936.870
20685            67859.560
20686             2069.190
20688              332.900
20689              620.050
20692             3699.760
20693              161.890
20694              626.080
20695              608.830
20696              633.180
20697              106.800
20698              114.450
20699              828.360
20700             1135.220
20701              721.490
20702             3385.950
20703             2010.470
20704             1371.420
20705              996.190
20707             1248.690
20711            26186.900
20712            38029.890
20713            41390.090
20714              649.820
20715              424.000
20716             1935.060
20717             7840.980
20718            17740.000
20719            28287.320
20721                0.850
20723            20677.620
20724            35595.630
20725            72292.850
20726            38949.730
20727            46422.490
20728            42784.740
20729             1778.120
20730             1011.700
20731             1254.170
20733             1481.100
20734             1485.680
20735             1589.030
20736              234.350
20737                1.700
20738             1301.720
20739                8.650
20747             9239.870
20748            14317.980
20749            22806.510
20750            27562.870
20751             6241.680
20752             2960.680
20753              509.000
20754            10608.750
20755             1105.800
20756              856.660
20757              914.500
20758              967.020
20759              895.380
20760             1317.910
20761             1475.200
20762             1381.530
20763              714.230
20764             2161.010
20765             1302.560
20766             1578.590
20767             1759.460
20768             1544.390
20769              819.010
20770             2218.360
20771             1229.730
20772             1866.500
20773              993.680
20774              977.330
20775              939.800
20776              834.310
20777             1280.970
20778              952.610
20780             1428.230
20781              611.280
20782             1105.440
20783             1056.890
20784             3570.870
20785             3672.350
20786             3533.900
20787             2535.100
20791               63.750
20793              518.500
20794              596.080
20795              308.700
20796              182.160
20798             1345.950
20799              355.330
20800              303.960
20801             1437.220
20802             1630.050
20803              903.500
20804              592.510
20812               12.750
20814              208.890
20816              123.600
20818              268.500
20819              635.240
20820               69.300
20821              286.420
20822                9.300
20823              555.470
20825             1255.080
20826              290.720
20827              209.360
20828            11095.910
20829             9892.240
20830              977.210
20831              940.560
20832             1143.710
20833              811.800
20835               98.040
20836              250.000
20837              188.070
20838              565.800
20839             1063.770
20840             1428.410
20845              502.270
20846             2000.730
20847              341.970
20848              115.050
20849              593.030
20850              713.800
20851              429.570
20854              747.730
20855              239.250
20856              688.940
20857              425.700
20858                6.600
20860               42.000
20861              100.800
20862              691.140
20863              605.730
20864              498.140
20865              500.490
20866             1381.440
20867             1154.450
20868              518.070
20869              296.370
20870               54.300
20871             1984.350
20877                5.040
20878              986.260
20879               75.600
20881                2.550
20882                8.850
20884                6.300
20885                2.950
20886             3589.500
20887              118.390
20888              547.740
20889              398.040
20890              202.620
20891              236.330
20892             1171.830
20893             1555.790
20894              871.550
20895               47.200
20896              118.000
20897              872.310
20898              693.920
20899              129.800
20901              812.930
20902             1588.800
20903              932.500
20905               63.500
20906              374.140
20910              794.520
20913              898.720
20914            53415.310
20931             2260.930
20932             1147.720
20933             1329.490
20934             1195.970
20935              580.380
20936              872.900
20939               10.200
20940              342.750
20941              898.790
20942                7.500
20943              543.960
20950              353.390
20952              151.140
20953               54.450
20954               25.590
20956             3179.000
20957              184.610
20958               70.500
20960             2570.920
20961             4901.570
20963             4937.620
20964               51.000
20966             4518.180
20967             4338.830
20968              185.110
20969            12315.100
20970             9632.000
20971            29027.460
20972            25151.840
20973             6930.470
20974             8895.240
20975            12266.780
20976              376.990
20977             5149.990
20978             5497.330
20979            10350.560
20980              283.560
20981             4125.990
20982             4309.250
20983             5521.780
20984             1959.840
20985             3081.760
20986             1591.090
20987              288.350
20988               46.800
20989              782.180
20990             1706.140
20991              884.560
20992             3285.580
20993             1334.110
20994               39.950
20996             1707.110
20997              796.740
20998              969.230
21000             1766.920
21001              754.960
21002             1547.540
21003              647.750
21004              625.070
21007              914.670
21008                2.510
21009             1509.990
21010             1122.260
21011             1415.850
21012             4457.000
21014             1040.360
21015              797.910
21016              584.550
21017              538.440
21018              203.920
21025              416.140
21026              730.500
21027              444.870
21028              426.410
21030              304.650
21031              181.710
21032              268.410
21033            10265.720
21034             4028.000
21035            18988.370
21036                2.550
21038              367.280
21039             3445.670
21040             1128.400
21041             9303.190
21042             8914.480
21043             1924.930
21051             1502.980
21054             3645.400
21055             4059.160
21056             5086.630
21058             2078.500
21059             1369.810
21060              962.750
21061             1078.010
21062              897.120
21063             1286.870
21064             4578.190
21065             1491.030
21066             1508.440
21067             3883.220
21068             4587.910
21069             5485.680
21070             2124.750
21071             5252.700
21076              715.400
21077             2060.650
21078             6213.390
21080            26031.970
21081                3.400
21082             1963.850
21084             1008.810
21085             1873.330
21086            10950.150
21087              168.080
21088             1816.730
21089              113.840
21090             1736.530
21091             1868.700
21092             1571.500
21094            15723.970
21095              281.370
21096             2715.960
21097               28.050
21098            14212.960
21099             1580.340
21100             3824.130
21102              221.080
21106             2455.090
21107             7075.400
21108            25887.350
21109             4573.150
21110             7830.830
21111             3300.600
21112             5531.500
21114             7462.160
21115             8065.730
21116             8099.220
21117              509.580
21118              104.250
21119               41.010
21120               33.960
21121            18979.330
21122            15455.060
21123             3435.560
21124            12254.050
21125             2270.140
21126             2372.980
21127             1003.980
21128              868.250
21129              970.290
21130             1204.380
21131             1098.860
21132              497.860
21133              736.570
21134              649.740
21135             8727.790
21136            17738.890
21137            69329.470
21143             4526.780
21144              294.190
21145             1256.210
21146             1537.070
21147              909.460
21153             4294.690
21154            12107.720
21155            16493.110
21156            17502.960
21157             1690.550
21158             1832.700
21159             1463.160
21160              558.940
21161             1846.120
21162             1661.860
21163             1802.520
21164            16865.400
21165            15359.800
21166            38560.160
21167              600.170
21169            14426.420
21171             2601.930
21172            11492.220
21173              611.260
21174            19864.320
21175            44391.430
21179             3570.870
21181            51005.820
21185              876.290
21186             8540.420
21187             2409.320
21188             2806.800
21189             1754.290
21190             1500.390
21191             3610.520
21192             4043.890
21193              274.370
21194              757.800
21195             2194.200
21196              308.540
21197              683.260
21198             1473.950
21199             1495.700
21200             2071.760
21201             6560.470
21202             1108.430
21203             2530.300
21204             2686.350
21205             1787.690
21206             3092.650
21207             5628.890
21208              980.270
21209             1369.690
21210            21957.260
21211             3390.290
21212            52997.200
21213            21734.850
21214             2922.270
21215             2607.300
21216            20528.580
21217            30483.030
21218            21102.060
21219             1340.820
21220              924.970
21221              740.940
21222              817.170
21223              592.080
21224             2756.950
21225                2.500
21226              234.300
21228              122.570
21231            24618.130
21232            50760.480
21238             8266.530
21239             6520.640
21240             6600.870
21241             1871.620
21242            11984.470
21243             9328.260
21244             8452.070
21245             4305.540
21246             3695.530
21247              666.220
21248             1309.700
21249             4862.040
21250             1003.450
21251             1704.610
21252              408.660
21253             1266.500
21255              860.080
21256              588.640
21257            14505.730
21258            24153.590
21259            14564.080
21260            11821.180
21261             1214.700
21262             2583.070
21263              683.820
21264              927.660
21265              717.410
21266               98.900
21267               74.600
21268              262.500
21269             1070.820
21270              899.930
21272             3163.650
21274             2446.190
21275             1748.380
21276             1558.940
21277             1397.190
21278             1685.050
21279             1637.010
21280             1800.440
21281             1747.280
21282             1577.530
21283             1710.450
21284             1694.050
21285             1383.670
21286             1638.190
21287             1893.750
21288             2595.840
21289             1594.310
21290                2.500
21291             2184.910
21292             1450.910
21293              872.340
21294             1778.750
21298              755.800
21299              966.350
21300              841.700
21303              985.540
21304              591.580
21306              350.650
21307              658.470
21308              705.900
21309              325.600
21310              179.700
21311              559.810
21312             1185.920
21313             5926.550
21314            25276.950
21316             1154.970
21317             1475.320
21318              903.720
21319              750.330
21320              913.340
21321              301.800
21322              590.450
21323             2523.890
21324             2898.820
21326            11972.480
21327             3476.940
21328             4836.130
21329             3857.200
21330             2460.670
21331              946.680
21332             1644.170
21333             3268.800
21335              989.620
21336              530.510
21337              103.530
21338              873.250
21339              544.500
21340            19541.460
21341              410.640
21343               92.000
21344              749.820
21347               47.600
21348             2039.690
21349             4139.330
21350              653.650
21351             3911.100
21352             3340.710
21353              160.450
21354             3050.820
21355             4315.580
21356             2071.800
21357             1841.510
21358             1422.470

In [26]:
# Merge revenue with main dataframe
df_5=df_5.merge(sku_revenue,on='StockCode',how='left')
df_5=df_5.sort_values(by='TotalRevenue',ascending=False).reset_index(drop=True)

In [27]:
# df_5.drop(columns=['TotalRevenue_y','TotalRevenue_x'],inplace=True)

# Cumulative % of Total Revenue
df_5['CumulativeRevenue'] = df_5['TotalRevenue'].cumsum()
df_5['CumulativeRevenuePercent']=df_5['CumulativeRevenue'] / df_5['TotalRevenue'].sum() * 100

# **ABC Analysis** 
- Insights :
    Overall revenue : £27.47M
    Category A revenue (£21.97M from 1,157 products) — A small group of products brings in most of the money
    Category B revenue (£4.12M from 1,462 products) — A mid-size group with moderate sales contribution
    Category C revenue (£1.37M from 2,813 products) — Most products individually contribute very little revenue

In [28]:
# Assign ABC category based on Total Revenue or  Pareto Analysis 80/20 rule 
def assign_abc(percent):
    if percent <=80:
        return 'A'
    elif percent <=95 :
        return 'B'
    else :
        return 'C' 

df_5['ABC_Category']=df_5['CumulativeRevenuePercent'].apply(assign_abc)

In [29]:
# Summary
pd.options.display.float_format = '{:,.2f}'.format
print(f'Total Revenue : {df_5['TotalRevenue'].sum()}')
print(f'\n{(df_5['ABC_Category'].value_counts()).to_string()}')
print(f'\n{(df_5.groupby('ABC_Category')['TotalRevenue'].sum()).to_string()}')
df_5.to_csv("final_inventory_with_abc.csv", index=False)

Total Revenue : 27475894.289

ABC_Category
C    2813
B    1462
A    1157

ABC_Category
A   21,978,688.40
B    4,122,819.76
C    1,374,386.13


# **Product Level : RFM Analysis** 

- Purpose: How fast, steady, and active is a specific product's demand?

- What it does: Tracks Recency (days since last purchase) and Frequency (total unique orders). Low recency and high frequency highlight fast-moving, predictable items, while high recency flags stagnant, dead stock.

In [36]:

print("\n Product-Level RFM & ABC Matrix ")

# Load raw transactional data
df_rfm = pd.read_csv("cleaned_retail.csv")
df_rfm["InvoiceDate"] = pd.to_datetime(df_rfm["InvoiceDate"])

# Reference point for recency
snapshot_date = df_rfm["InvoiceDate"].max() + pd.Timedelta(days=1)

# Calculate RFM per Product (StockCode) 
product_rfm = (df_rfm.groupby("StockCode").agg( Product_Recency=( "InvoiceDate", lambda x: (snapshot_date - x.max()).days),
                                                Product_Frequency=( "Invoice", "nunique"), 
                                                Product_Monetary=( "Revenue", "sum")
                                            )
                                            .reset_index()
                )

# Merge the Product RFM metrics directly into your ABC DataFrame 
rfm_abc_matrix = df_5.merge(product_rfm, on="StockCode", how="left")

# Create simple actionable scores (Using quantiles/percentiles)
# High Frequency (Top 50% most frequently ordered items) -> 'Fast Mover'
# Low Frequency (Bottom 50%) -> 'Slow Mover'
freq_threshold = rfm_abc_matrix["Product_Frequency"].median() # threshold

rfm_abc_matrix["Velocity_Segment"] = rfm_abc_matrix["Product_Frequency"].apply(lambda x: "Fast-Moving" if x >= freq_threshold else "Slow-Moving")

# Create a combined strategy tag (e.g : "A / Fast-Moving" or "C / Slow-Moving")
rfm_abc_matrix["Inventory_Strategy_Tag"] = (rfm_abc_matrix["ABC_Category"] + " - "+ rfm_abc_matrix["Velocity_Segment"])


# print(rfm_abc_matrix[["StockCode", "ABC_Category", "Product_Recency", "Product_Frequency", "Inventory_Strategy_Tag"]].head(10).to_string(index=False))
print(rfm_abc_matrix['Inventory_Strategy_Tag'].value_counts())

 Product-Level RFM & ABC Matrix

C:\Users\DELL\AppData\Local\Temp\ipykernel_7928\2529041312.py:4: DtypeWarning: Columns (0: Invoice) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rfm = pd.read_csv("cleaned_retail.csv")

Inventory_Strategy_Tag
C - Slow-Moving    2438
B - Fast-Moving    1206
A - Fast-Moving    1130
C - Fast-Moving     375
B - Slow-Moving     256
A - Slow-Moving      27
Name: count, dtype: int64

# **Statistical Analysis** 

- Purpose : Understand demand patterns

- What it does: calculates average, middle value and spread of daily sales for each product. Useful for spotting which products have steady demand versus wildly unpredictable demand.

In [31]:

print("\n Statistical Analysis ")
df_stats = pd.read_csv('daily_demand.csv')

demand_stats = df_stats.groupby('StockCode')['DailyQty'].agg(['mean', 'median', 'std', 'min', 'max']).reset_index()
demand_stats.columns = ['StockCode', 'AvgDemand', 'MedianDemand', 'StdDev', 'MinDemand', 'MaxDemand']

print(demand_stats.head())

 Statistical Analysis

C:\Users\DELL\AppData\Local\Temp\ipykernel_7928\2395480042.py:2: DtypeWarning: Columns (0: StockCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df_stats = pd.read_csv('daily_demand.csv')

  StockCode  AvgDemand  MedianDemand  StdDev  MinDemand  MaxDemand
0     21713      12.30          8.00   20.76          1        154
1     21714      15.50          8.00   30.70          1        442
2     21715      11.72          8.00   24.47          1        297
3     21716      12.46          8.00   25.21          1        320
4     21717      14.07          8.00   15.95          1         96

# **Hypothesis Testing**
- Purpose : Is demand actually higher on weekdays than weekends or is that just random?

- What it does: Runs a t-test to compare two groups. A p-value under 0.05 means the difference is real, not random.

In [32]:

print("\n Hypothesis Testing ")
df_hypo = pd.read_csv('daily_demand.csv')
df_hypo['Date'] = pd.to_datetime(df_hypo['Date'])
df_hypo['DayType'] = df_hypo['Date'].dt.dayofweek.apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')

weekday_demand = df_hypo[df_hypo['DayType'] == 'Weekday']['DailyQty']
weekend_demand = df_hypo[df_hypo['DayType'] == 'Weekend']['DailyQty']

t_stat, p_value = stats.ttest_ind(weekday_demand, weekend_demand)

print(f"P-value: {p_value:.4f}\n")
if p_value < 0.05:
    print("Result: Weekday and weekend demand are genuinely different (not random).")
else:
    print("Result: No real difference - the gap could just be random variation.")

 Hypothesis Testing

C:\Users\DELL\AppData\Local\Temp\ipykernel_7928\775392162.py:2: DtypeWarning: Columns (0: StockCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df_hypo = pd.read_csv('daily_demand.csv')

P-value: 0.0000

Result: Weekday and weekend demand are genuinely different (not random).

# **Regression Analysis** 
- Purpose  : Is demand trending up or down for a specific product over time?

- What it does: Fits a simple trend line through a product's daily sales. A positive number means demand is growing over time, negative means it's shrinking.

In [33]:

def run_regression_analysis(stock_code):
    print("\n Regression Analysis ")
    df_reg = pd.read_csv('daily_demand.csv')
    df_reg['Date'] = pd.to_datetime(df_reg['Date'])

    sku_data = df_reg[df_reg['StockCode'] == stock_code].sort_values('Date')
    if sku_data.empty:
        print(f"No data found for StockCode {stock_code}")
        return

    sku_data['DayNumber'] = (sku_data['Date'] - sku_data['Date'].min()).dt.days

    # Define input features and target variable
    X = sku_data[['DayNumber']]
    y = sku_data['DailyQty']

    X_with_constant = sm.add_constant(X) 
    model = sm.OLS(y,X_with_constant)

    results = model.fit()

    trend = results.params["DayNumber"] # Extract coefficent value
    p_value = results.pvalues['DayNumber']

    print(f"Product: {stock_code} \n")
    print(f"Trend per day: {trend:.2f} \n")

    if p_value < 0.05 :
        print("Demand is rising" if trend > 0 else "Demand is falling ")
        print(f"-> This trend is statistically significant (p-value: {p_value:.4f})")
    else:
        print("Demand is flat / no significant trend change")
        print(
            f"-> Any slight shift is likely random chance (p-value: {p_value:.4f} > 0.05)"
        )

    print(results.summary())

# Function Calling 
run_regression_analysis(stock_code='85123A')

 Regression Analysis

C:\Users\DELL\AppData\Local\Temp\ipykernel_7928\2037222634.py:3: DtypeWarning: Columns (0: StockCode) have mixed types. Specify dtype option on import or set low_memory=False.
  df_reg = pd.read_csv('daily_demand.csv')

Product: 85123A

Trend per day: -0.17

Demand is falling
-> This trend is statistically significant (p-value: 0.0001)
                            OLS Regression Results
==============================================================================
Dep. Variable:               DailyQty   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.025
Method:                 Least Squares   F-statistic:                     16.64
Date:                Sat, 10 Oct 2026   Prob (F-statistic):           5.13e-05
Time:                        20:55:01   Log-Likelihood:                -4103.0
No. Observations:                 604   AIC:                             8210.
Df Residuals:                     602   BIC:                             8219.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        223.1239     17.765     12.560      0.000     188.235     258.013
DayNumber     -0.1681      0.041     -4.079      0.000      -0.249      -0.087
==============================================================================
Omnibus:                      813.512   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           140813.147
Skew:                           6.924   Prob(JB):                         0.00
Kurtosis:                      76.508   Cond. No.                         871.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.